### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: require() of ES Module

### ISSUE THREAD

**Issue by shauntrennery** [alexghr/got-fetch#70]
Getting an error when upgrading to v5

`const { fetch } = require('got-fetch');`

**Comment by alexghr** [comment]
Hey, that's expected unfortunately (I should've updated the readme). `got` v12 is [a pure ESM package](https://github.com/sindresorhus/got/releases/tag/v12.0.0) now and can only be imported by other ESM packages.

I had to migrate `got-fetch` v5 to be an ESM module because of this and any packages depending on `got-fetch` v5 will have to do the same thing. The `got` developers came up with a [FAQ in this gist](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c) about pure ESM packages. Have a look there, maybe something will work for your project? Regardless, I will keep maintaining `got-fetch` v4 for as long as its needed.

I will update the README here to talk about ESM vs CJS and I will create a maintenance branch for `got-fetch` v4.
